# Generated by Django 4.2.1 on 2023-05-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='imagem_bar')),
                ('local', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='imagem_cafe')),
                ('local', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jantar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='imagem_jantar')),
                ('local', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='imagem_passeio')),
                ('local', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='imagem_praia')),
                ('local', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='treep.bar')),
                ('cafe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='treep.cafe')),
                ('jantar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='treep.jantar')),
                ('passeio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='treep.passeio')),
                ('praia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='treep.praia')),
            ],
        ),
    ]
